# Generated by Django 3.2.7 on 2021-10-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follows_likes_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
